scripts/readscount.py
code needs to be 2.6 compatible since it's what is run on the epp virtualenv.
=> 2.6 compatibility

scripts/undemultiplexed_index.py
I also set the "Include reads" field automatically based on QC. Would like to have this merged asap
=> A small add to the script

scripts/undemultiplexed_index.py
=> set run id before

scripts/bravo_csv.py
EPP for the setup workset plate
=> added modifs required by validation

scripts/bravo_csv.py, scripts/readscount.py
They need the set total read column filled in in order to advance to the next step.
=> Help the lab

scripts/copy_qubit.py
=> qubit 3.0 2.0 !

scripts/readscount.py
=> sample has no udf named that way, but the output artifact does

scripts/bravo_csv.py
these need to be floats, else it summons cthulhu
=> calc as floats

LICENSE, genologics/entities.py
naming the logger,adding the license and extending the review data.
=> Small changes

genologics/lims.py
Added support to query artifacts based on the lims id of a sample.
=> Add query artifacts based on lims sample id

scripts/zebra_barcodes.py
but the other way around this is having chuan spend two hours resetting every call to this script, so he'd rather have these two lines.
=> that's not nice

genologics/entities.py
It seems like psul sometimes breaks over this.
=> should improve the reliability of this specific part

genologics/entities.py, genologics/lims.py, scripts/read_neoprep_log.py, scripts/write_neoprep_csv.py
This adds two epps and a way to get file contents through the lims object.
=> neoprep epps

scripts/undemultiplexed_index.py
=> added another truseq flowcell

genologics/entities.py
Several more updates to match the version 3.5
=> updates to 3.5

genologics/entities.py
I like the udfs to behave like dictionnaries.
=> update on udfs

genologics/entities.py
=> UdfDictionary fixes

scripts/bravo_csv.py
=> make the bravo csv for the genotyping step

scripts/bravo_csv.py
Some changes to how the volumes are calculated:
- Only optimize pooling volumes when input volumes differ
- Calculate a final concentration for the above case
=> Updates to the pool volume calculator

genologics/lims.py
Apparently, it's completely broken :D
=> Revert "Batch calls"

scripts/comments_to_running_notes.py
This updates the comments EPP. Some thinking is still required as to how to use it.
=> Comments EPP

scripts/tecan_parser.py
Chnaged so that results are assigned by output position instead of input.
=> Fix in plate reader result parser EPP

scripts/copy_qubit.py
- Semi-colon-delimited files now works
- Result file contents are now read using lims.get_file_contents
=> Add support for alternative csv formats

scripts/bravo_csv.py
Using our own instead of Genologics’ will make the pre-pooling script work better as well as provide correct plate id's for the barcode checking on the robot.
=> Added csv generator for the Library Normalization process

scripts/bravo_csv.py
The container ID's rather than plate names are used in the csv file so it matches the plate barcode (except in "Setup workset/plate").
=> Added fix for renamed plates

scripts/write_neoprep_csv.py
Adding constraints for neoprep epp when using <16 samples
=> neoprep wants 16 lines, give it 16 lines

genologics/entities.py
Checking only with str fails in the case of unicode.
=> getting python 2 to work again with unicode

tests/test_entities.py
Sorry about the py2/3 compatibility issues.
I added a test for the bug you just fixed.
hopefully more will help going forward
=> add test for unicode values in UDFdictionaries

tests/test_entities.py
=> Add comparison method for ElementTree

scripts/tecan_parser.py
Show an error message if the concentration CV for any well is above 20 when parsing the Tecan plate reader result file.
=> Display error message for high CV's

scripts/molar_concentration.py
if one of the fields is zero, it messes everything up. now it doesnt.
=> fixing concentration calculation for bad samples

scripts/tecan_parser.py
Convert CV value from string to float so the comparison actually works
=> Fix check for high CV

genologics/descriptors.py
Forgot an import in previous PR
I don't know if you want me to increment the version for that.
=> Fix missing import

genologics/entities.py
=> adding name to ReagentType

genologics/entities.py
Added classmethod create to Step class.
=> Add support for step creation

genologics/entities.py
Updated the class Step(Entity) to include the tags for date-started and date-completed.
=> Added date-started and date-completed tags
